### ISSUE TITLE
Can we have traits  for lada-cache

### ISSUE THREAD

**Issue by george1974** [spiritix/lada-cache#34]
Can we have traits instead of all models extending the Spiritix\LadaCache\Database\Model class? It would make more sense if lada-cache going forward uses traits for peaceful co-existence with other classes.

**Comment by spiritix** [comment]
Yes, we can do that. However, you will still need to put the trait in all models or create a base model with the trait in it which gets extended by all other models.

**Comment by qodeboy** [comment]
Looks like the only thing ```Spiritix\LadaCache\Database\Model``` class does is overrides ```newBaseQueryBuilder``` method, which can be easily put into trait on project level. My concern is that package can check if model is actually extending from ```Spiritix\LadaCache\Database\Model``` when doing caching, but after quick review I couldn't find any traces of such check.

@spiritix can you please let us know if it's save to put ```newBaseQueryBuilder``` into trait on the project level?

**Comment by spiritix** [comment]
Indeed, this should be the only thing required to get traits working. Since this will be a breaking change a new major version would be required in order to release this feature and the documentation would need to be updated. At the moment I am involved in a lot of projects and can't find the time for that, so contributions are welcome.

**Comment by spiritix** [comment]
Will be included in today's release. Thanks for your patience guys.
