### ISSUE TITLE
Queries built by Eloquent\Builder instead of Query\Builder bypass the cache

### ISSUE THREAD

**Issue by roxik** [spiritix/lada-cache#46]
I use $product->withCount('screens')->get();

On $screen->destroy($id), screens_count not updated.

**Comment by spiritix** [comment]
The problem here is that Laravel usually builds all queries using the Illuminate\Database\Query\Builder class. However, the withCount() queries are built using the Illuminate\Database\Eloquent\Builder class which Lada Cache has no access to. In the Query\Builder class, we only have access to the raw SQL which doesn't help us, since this would require an SQL parser to be implemented. The only way to get this working would be routing the entire logic from Eloquent\Builder trough Lada Cache then somehow merge it with Query\Builder. This isn't trivial and will require some time, PRs are welcome.

**Comment by spiritix** [comment]
See #47 and #48, they are probably caused by this issue as well.

**Comment by roxik** [comment]
When you are able to solve a problem?

**Comment by spiritix** [comment]
I can't tell you a date, will look at it as soon as I can find some time. Like I said above, this isn't something which can be done in ten minutes. If this is urgent for you, please feel free to contribute to the project and create a pull request.

**Comment by Swanty** [comment]
@spiritix Yes the aggregate error happens randomly and as I said I can't reproduce it on dev or staging server. It happens only on production server which has high load at all times, so that's why I'm guessing it's related to timing of Redis cache invalidation.

Aggregate error simply happens when we call `$article->comments()->count()`
But as I said I can't reproduce it. I debugged using xdebug and everything seemed fine, there was "aggregate" array key and it had the count.
So I came to conclusion it's related to when Redis invalidates a key, thus the aggregate array key no longer exists.
My guess is that Redis invalidates key, something either in Laravel or LadaCache doesn't detect it and thus we get error. If it was detected then it should just query directly from database again, but it doesn't do that and throws error.
Could it be something related to Redis tags? Like for example we get key from Redis which points to tags, but the tags in the mean time have expired? As in - first key was ok, but while we're getting the next key it's already gone and we get error instead of fetching from db again?

**Comment by spiritix** [comment]
Indeed, if the tag items in Redis would expire before the items containing the cached values, this would result in the described behavior.
Have a look here: https://github.com/spiritix/lada-cache/blob/master/src/Spiritix/LadaCache/Cache.php#L90
As you can see, there is no expiration time set for the tags, so it uses the configured server's default time. For the query items, however, it uses the expiration time set in [here](https://github.com/spiritix/lada-cache/blob/master/config/lada-cache.php#L37).

**Comment by spiritix** [comment]
To update on this: 

> My guess is that Redis invalidates key, something either in Laravel or LadaCache doesn't detect it and thus we get error.

Lada Cache will never detect if a key was deleted/invalidated in Redis if the corresponding query wasn't made through Lada Cache. Otherwise, it would have to scan on each tick for deleted keys which would be a massive performance flaw. We have two possible causes here:

a) An update query bypasses Lada Cache. But if so, this would occur consistently, and not only sometimes.

b) Some keys in Redis get deleted by whatever mechanism which is not related to Lada Cache. If so, this is not something we can fix in Lada Cache, but we should figure out what it's caused by an update the manual on how to avoid it. 

Anyway, that's for sure not caused by the issue described in here. The problems caused by sub-queries and queries built by Eloquent directly are always reproducible.

**Comment by roxik** [comment]
@spiritix there is a solution?

can change redis config?

**Comment by spiritix** [comment]
The only thing you can do is making sure that items in Redis don't get deleted for whatever reason other than explicitly. Otherwise, you will have to dig a bit deeper and check when and why the keys get deleted and what causes the deletions. I can't help you with that as I can't reproduce it.

**Comment by roxik** [comment]
how can keys be removed if from there obtains data?

**Comment by spiritix** [comment]
Probably the keys for the tags are removed, not the query keys. And this leads to queries not being invalidated anymore.

**Comment by roxik** [comment]
how to check it?

**Comment by spiritix** [comment]
Watch for changes using notifications https://redis.io/topics/notifications

**Comment by roxik** [comment]
if keys are lost, what to do?

**Comment by spiritix** [comment]
Trigger a stack trace to see what causes the keys to be deleted.

**Comment by roxik** [comment]
how exactly to make it?

**Comment by roxik** [comment]
go to im chat?

**Comment by spiritix** [comment]
Yes, we should not use GitHub as a chat. Will delete all comments in here which don't belong to the topic. Please send me an email to the email address on my profile and I will hit you up for IM details.

**Comment by roxik** [comment]
I sent an email to

**Comment by spiritix** [comment]
Will be solved in today's release. Thanks for your patience.
