### ISSUE TITLE
multiple database connections

### ISSUE THREAD

**Issue by hurano** [spiritix/lada-cache#51]
It seems like its not working when I have multiple database connections.
https://laravel.com/docs/5.5/database#using-multiple-database-connections

**Comment by spiritix** [comment]
I've now further investigated this problem. Unfortunately, it seems that there is no easy solution for it. The authors of Laravel have hardcoded the database connections [here](https://github.com/laravel/framework/blob/bd352a0d2ca93775fce8ef02365b03fc4fb8cbb0/src/Illuminate/Database/Connectors/ConnectionFactory.php#L269) instead of resolving them from the IoC container like properly done in other places.
In order to get this working, we'd have to override the DB facade and all subsequent classes until we reach the ConnectionFactory.

Anyhow, there is a pretty simple fix:
Instead of using `DB::connection('foo')` just specify the `$connection = 'foo';` parameter in your model and it will work fine.

**Comment by spiritix** [comment]
Added a limitation to the docs.
