### ISSUE TITLE
any idea if this would be compatible with mongodb?

### ISSUE THREAD

**Issue by vesper8** [spiritix/lada-cache#52]
I use https://github.com/jenssegers/laravel-mongodb/ and I use it in combination with mysql.. it works great and most packages also work out of the box.. but this one I'm not so sure since it interacts a lot with eloquent and laravel-mongodb uses its own eloquent sort of

**Comment by spiritix** [comment]
Please excuse my late answer. I don't think it will work out of the box since the Laravel database connections must be routed via Lada Cache (as you can see here https://github.com/spiritix/lada-cache/tree/master/src/Spiritix/LadaCache/Database/Connection). However, I think with some minor adjustments it shouldn't be a problem to get it working.
