### ISSUE TITLE
Maybe add a How It Works section to README.md

### ISSUE THREAD

**Issue by phpguru** [spiritix/lada-cache#57]
This project looks great, but I had some technical questions about how lada-cache actually works. 

1. Does it make an MD5 of the query via toSql() or [another object](https://github.com/spiritix/lada-cache/blob/master/src/Spiritix/LadaCache/Hasher.php#L52) and check if that exists? 
1. How would I inspect the keys created by lada-cache in Redis CLI? 
1. How long are the TTLs for query results cached? 
1. If a new field data is written to the db, how does the query cached become invalidated?
1. How are cached query results serialized into Redis? 
1. Can it be used with PHPRedis (not Predis)?

Without looking at the actual source code it is difficult to understand what is actually happening, which, I believe, is an important factor to decide if this library is right for me.

**Comment by spiritix** [comment]
Good suggestion, thanks. Created a Wiki with two articles as a starting point: https://github.com/spiritix/lada-cache/wiki

Regarding PHPRedis: I currently don't see a reason to implement this, Predis (especially combined with [phpiredis](https://github.com/nrk/phpiredis)) is just much faster and more stable.

**Comment by phpguru** [comment]
I have always used PHPRedis over predis for C code speed execution. I didn't realize that phpiredis seems to be the preferred way to connect to Redis from PHP nowadays. Thanks for the wiki!

**Comment by spiritix** [comment]
Well, I don't advise anyone against using PHPRedis, the thing is just Lada Cache should not have hard dependencies on the server side since a lot of users wouldn't be able to install them. Therefore PHPRedis wasn't an option at all, at least not as default driver. Regarding speed, I'd strongly suggest installing `phpiredis`, it's actually pretty fast since it's based on `hiredis` which is also written in C.
