### ISSUE TITLE
updateExistingPivot method doesn't invalidate data

### ISSUE THREAD

**Issue by rbruhn** [spiritix/lada-cache#60]
Just wondering if there is a way to bypass the cache. For example, while doing a cron job and wanting direct query result, not a cached version. Or, do I simply need to flush the cache before doing the cron job?

Thanks

**Comment by spiritix** [comment]
Actually, the idea is that the cache should always return the most current version of your data, so it shouldn't be required to do that. If you still want to be on the safe side or if you have some code which interferes with the cache, you can try doing the following:

```
config(['lada-cache.active' => false]);
// Cronjob...
config(['lada-cache.active' => true]);
```

Flushing the cache on runtime can be done like this:

```
Artisan::call('lada-cache:flush');
```

Hope this helps.

**Comment by rbruhn** [comment]
I'm using stats on a pivot table that get updated each night. The pivot table has its own id, but does not invalidate the cache when updated. Perhaps because I'm not using the Id itself?
An example:
```
$expeditions = $this->expedition->getExpeditionsForNfnClassificationProcess();
$expeditions->each(function($expedition){
    $attributes = [
            'queued'    => 0,
            'completed' => 1
    ];
    $expedition->nfnActor->expeditions()->updateExistingPivot($expeditionId, $attributes);
});
dd($expeditions->count());
```
The above does update. However running the test again I always end up with the same expeditions from the cache.

**Comment by spiritix** [comment]
It is possible that there is a bug with the `updateExistingPivot` method. I will have a look at it once I have some time. Until then, flushing the cache after your cronjobs might be a good idea indeed.

**Comment by rbruhn** [comment]
Ya, already put that into the scheduler. Thanks.

**Comment by fede91it** [comment]
I also have a similar problem, updating to a pivot record does not invalidate the cache and the subsequent query returns the old pivot attributes as if they had not been changed.

I'd like to help fix the bug but I don't know where to start. In your opinion which classes of lada source files could be the starting point to identify the problem?

**Comment by spiritix** [comment]
Sure, I would greatly appreciate any contributions as my time currently is very limited. In order to properly debug the cache make sure you have PHPUnit and the Laravel Debugbar installed.

The invalidation works like this: 
1. We override every method in Laravel's QueryBuilder.php that can possibly change data in DB (see https://github.com/spiritix/lada-cache/blob/master/src/Spiritix/LadaCache/Database/QueryBuilder.php#L97)
2. The QueryHandler handles the invalidation flow by getting tags from the query (see https://github.com/spiritix/lada-cache/blob/master/src/Spiritix/LadaCache/QueryHandler.php#L174)
3. The invalidator removes all relevant items from the cache (see https://github.com/spiritix/lada-cache/blob/master/src/Spiritix/LadaCache/Invalidator.php#L49)

Also, please have a look at the Wiki which explains how the library works in general: 
https://github.com/spiritix/lada-cache/wiki

Now I could think of the following causes for the mentioned issue:
- There's an override missing for a method in QueryBuilder
- The Tagger is not able to retrieve all required information from the query 

Pay attention that sub-queries are handled separately (see https://github.com/spiritix/lada-cache/blob/master/src/Spiritix/LadaCache/Database/QueryBuilder.php#L82). Since Laravel sometimes compiles sub-queries to actual SQL (which this library cannot parse) immediately, this could be a possible cause as well.

**Comment by fede91it** [comment]
Works perfectly using your Pivot class. 🎉

**Comment by spiritix** [comment]
Should be fixed with latest release. Currently testing it.
