### ISSUE TITLE
Working for shared hosting (Question)

### ISSUE THREAD

**Issue by aozen** [spiritix/lada-cache#65]
Is this working for shared hosting? As i known redis is not working. Redis want your own server. I am looking to implement a cache system all of our project. Thanks in advance.

**Comment by spiritix** [comment]
It is working fine for shared hostings, I'd even say that the performance gain Lada Cache provides is much bigger if all services are running on a single server since there is no network overhead. Redis doesn't require a standalone server, it runs smoothly on a shared server. Nevertheless, the requirement is obviously that your hosting provider has Redis installed since shared hostings usually don't allow installing software by yourself.
